#!/usr/bin/env bash

# get directory of this script
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$SCRIPT_DIR/dotfiles.lib"

USERNAME=$(whoami)
export OPT="$HOME/opt"

mkdir -p "$OPT"

bundles="${@}"

if [[ -z $bundles ]]; then
  source $SCRIPT_DIR/bundles/base.sh
fi


include_bundles "$bundles"
