#!/bin/bash
#
# mohabaks, 21 Oct 2016 22:36
# https://github.com/mohabaks
# Lemonbar Configs
#

#************** Colors ******************
. $HOME/bin/color-parser

#************** Panel ******************
PW=1366
PH=24
PX=0
PY=0


#*************** Fonts *****************
FONT1="Iosevka:size=9"
FONT2="Siji:size=8"
FONT3="FontAwesome:size=12"


#*************** Icons ******************
