default-remote: local
remotes:
  images:
    addr: https://images.linuxcontainers.org
    public: true
    protocol: simplestreams
  local:
    addr: unix://
    public: false
    project: default
aliases:
  delete: delete -f
  ls: list -c ns46
  shell: exec @ARGS@ -- bash
  u: exec @ARGS@ -- sudo --login --user ubuntu
